### ISSUE TITLE
Clangd not detecting modules without recompilation with CMake

### ISSUE THREAD

**Issue by Froggy111** [ChuanqiXu9/clangd-for-modules#16]
When non-std module imports are removed, cmake build, then added back, clangd does not find the modules, and a cmake build has to be done again and clangd restarted for the non-std module to be detected.

**Comment by ChuanqiXu9** [comment]
This is the assumption of the current supports of clangd in modules. We need information from build systems and the compilation database is the bridge. And the compilation database can only be built by the build system.

**Comment by Froggy111** [comment]
Is there some workaround to quickly regenerate the compilation database on change?

**Comment by ChuanqiXu9** [comment]
I didn't know it and I am not sure if it is possible

**Comment by Froggy111** [comment]
Ok, thanks! I'll close this now.
